//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPLAY
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string VIDEO_PROCESSOR { get; set; }
        public string MANUFACTURER { get; set; }
        public Nullable<int> VIDEO_ARCHITECTURE { get; set; }
        public string DAC_TYPE { get; set; }
        public Nullable<double> MEMORY_SIZE { get; set; }
        public Nullable<int> MOUSE { get; set; }
        public string VIDEO_MODE { get; set; }
        public Nullable<int> CURRENT_REFRESH_RATE { get; set; }
        public string DRIVER_VIRSION { get; set; }
        public string DRIVER_DATE { get; set; }
    }
}
