//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DriverUpdaterDataStoreEntities : DbContext
    {
        public DriverUpdaterDataStoreEntities()
            : base("name=DriverUpdaterDataStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DISPLAY> DISPLAYs { get; set; }
        public virtual DbSet<DRIVER_DETAILS> DRIVER_DETAILS { get; set; }
        public virtual DbSet<DRIVE> DRIVES { get; set; }
        public virtual DbSet<InfoBlockOverAll> InfoBlockOverAlls { get; set; }
        public virtual DbSet<LICENSE> LICENSEs { get; set; }
        public virtual DbSet<MEMORY_DEVICE> MEMORY_DEVICE { get; set; }
        public virtual DbSet<OS> OS { get; set; }
        public virtual DbSet<PROCESSOR_AND_MOTHERBOARD> PROCESSOR_AND_MOTHERBOARD { get; set; }
        public virtual DbSet<ScanResultCheckBoxValue> ScanResultCheckBoxValues { get; set; }
        public virtual DbSet<TIME_STAMPS> TIME_STAMPS { get; set; }
    }
}
