//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRIVE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public string INTERFACE_TYPE { get; set; }
        public Nullable<int> PARTITIONS { get; set; }
        public Nullable<int> TOTAL_CYLINDERS { get; set; }
        public Nullable<int> TOTAL_HEADS { get; set; }
        public Nullable<int> TOTAL_SECTORS { get; set; }
        public Nullable<int> TOTAL_TRACKS { get; set; }
        public Nullable<int> TRACKS_PER_CYLINDERS { get; set; }
        public Nullable<int> BYTES_PER_SECTOR { get; set; }
        public Nullable<int> SECTORS_PER_TRACK { get; set; }
    }
}
