//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRIVER_DETAILS
    {
        public int ID { get; set; }
        public string FRIENDLY_NAME { get; set; }
        public string CATEGORY { get; set; }
        public string CURRENT_DATE { get; set; }
        public string DRIVER_VIRSION { get; set; }
        public string MANUFACTURER { get; set; }
        public string DEVICE_ID { get; set; }
        public string HARDWARE_ID { get; set; }
        public string INF_NAME { get; set; }
        public byte[] FILE_CONTENT { get; set; }
        public string DRIVER_DATE { get; set; }
        public string CREATED_AT { get; set; }
        public string UPDATED_AT { get; set; }
    }
}
