//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoBlockOverAll
    {
        public int Id { get; set; }
        public string OPERATING_SYSTEM { get; set; }
        public string PROCESSOR { get; set; }
        public string GRAPHICS_CARD { get; set; }
        public Nullable<double> MEMORY { get; set; }
        public string MONITOR { get; set; }
        public Nullable<double> DISK_STORAGE { get; set; }
        public string AUDIO { get; set; }
        public string MOTHERBOARD { get; set; }
        public string MOUSE { get; set; }
        public string KEYBOARD { get; set; }
    }
}
