//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICENSE
    {
        public int ID { get; set; }
        public string LICENSE_KEY { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public Nullable<System.DateTime> VALID_TILL { get; set; }
        public string ACTIVATED_MACHINE { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
    }
}
