//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMORY_DEVICE
    {
        public int ID { get; set; }
        public Nullable<double> TOTAL_MEMORY { get; set; }
        public string MEMORY_BANK { get; set; }
        public string DESCRIPTION { get; set; }
        public string DEVICE_LOCATOR { get; set; }
        public Nullable<double> CAPACITY { get; set; }
        public Nullable<int> SPEED_LABEL { get; set; }
        public string MANUFACTURER { get; set; }
        public Nullable<int> DATA_WIDTH { get; set; }
        public Nullable<int> MEMORY_TYPE { get; set; }
        public Nullable<int> FORM_FACTOR { get; set; }
    }
}
