//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OS
    {
        public int ID { get; set; }
        public string COMPUTER_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string ORAGNISATION { get; set; }
        public string OS_NAME { get; set; }
        public string OS_VERSION { get; set; }
        public string PRODUCT_ID { get; set; }
        public Nullable<int> ARCHITECTURE { get; set; }
    }
}
