//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSOR_AND_MOTHERBOARD
    {
        public int ID { get; set; }
        public string CPU_NAME { get; set; }
        public string NO_LOGICAL_PROCESSORS { get; set; }
        public string MANUFACTURER { get; set; }
        public Nullable<int> CURRENT_CLOCK_SPEED { get; set; }
        public Nullable<int> MAX_CLOCK_SPEED { get; set; }
        public Nullable<double> VOLTAGE { get; set; }
        public Nullable<int> EXTERNAL_CLOCK { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string CPU_ID { get; set; }
        public string SOCKET_DESIGNATION { get; set; }
        public Nullable<int> L2_CACHE { get; set; }
        public Nullable<int> L3_CACHE { get; set; }
        public string MODEL { get; set; }
        public string PMANUFACTURER { get; set; }
        public string PSERIAL_NUMBER { get; set; }
        public string BIOS_NAME { get; set; }
        public string BIOS_VENDOR { get; set; }
        public string SMBIOS_VERSION { get; set; }
        public Nullable<bool> PCI_SUPPORT { get; set; }
        public Nullable<bool> BIOS_UPGRADABLE { get; set; }
        public Nullable<bool> BIOS_SHADOWING { get; set; }
        public Nullable<bool> BOOT_FROM_DISK { get; set; }
        public Nullable<bool> SELECTABLE_SUPPORTED { get; set; }
        public Nullable<bool> EDD_SUPPORT { get; set; }
        public Nullable<bool> ACPI_SUPPORT { get; set; }
        public Nullable<bool> USB_LAGACY_SUPPORT { get; set; }
    }
}
