//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanResultCheckBoxValue
    {
        public int Id { get; set; }
        public string NAME { get; set; }
        public Nullable<bool> VALUE { get; set; }
    }
}
