//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver_Updater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME_STAMPS
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LAST_SCAN { get; set; }
        public Nullable<System.DateTime> PRODUCT_REGISTRATION { get; set; }
        public Nullable<System.DateTime> LAST_BACKUP_TIME { get; set; }
    }
}
